[package]
name = "easylink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.11.0", features = ["attributes", "tokio1"] }
futures-util = "0.3"

dashmap = "5.3.4"
lazy_static = "1.4.0"
once_cell = "1.4.0"
rand = "0.8.5"
rand_core = "0.5"
num_cpus = "1.0"

async-tungstenite = "*"
warp = "0.3.2"

mediasoup = "0.9.3"

mongodb = "2.2.1"
jsonwebtoken = "8.1.0"

serde = { version = "1.0.137", features = ["derive"] }
rmp-serde = "0.13.7"

aes-gcm = "0.9.4"
flate2 = "1.0.23"
x25519-dalek = "1.2.0"
